### ISSUE TITLE
Saved charset for stations aren't used on start

### ISSUE THREAD

**Issue by ronsens** [sdushantha/pyradio#4]
Hi,
version 0.8.9.31 on Linux.

On start the standard charset is used for every station - even for those where a different one has been set and stored in the station settings (I also checked the .csv-File which seems correct),

![1 On start](https://user-images.githubusercontent.com/11320279/204032657-06cdb026-610c-4668-81af-d2c468a1eb68.png)

When I go in Edit Mode for these stations I also see that the different / whished charset is set as saved before:

![2 Set settings for station](https://user-images.githubusercontent.com/11320279/204032653-019f26bf-8e74-4bb7-917b-02c977d69b59.png)

 and when I press OK again   -   the "correct" charset is then used for this station - but only for the current session of pyradio (means: on restart the charset settings stored in the settings / .csv are ignored again). 

![3 Correct charset chosen (only after saving again in Edit Mode)](https://user-images.githubusercontent.com/11320279/204032648-fba299d1-a308-4ac8-848a-9cc9510241a2.png)

Thanks!

**Comment by sdushantha** [comment]
Hi @ronsens, I think you have found the wrong repo. The one you're probably looking for is this one: https://github.com/coderholic/pyradio

I didn't know that project existed so that's why my project and the one mentioned above have the same name. Sorry about that 😅

**Comment by ronsens** [comment]
Dear Siddharth,

thanks for your kind and swift anser. That was very stupid of me, should have checked it by myself before!

Kind regards


On Sat, 26 Nov 2022 04:41:13 -0800
Siddharth Dushantha ***@***.***> wrote:

> Hi @ronsens, I think you have found the wrong repo. The one you're probably looking for is this one: https://github.com/coderholic/pyradio
> 
> I didn't know that project existed so that's why my project and the one mentioned above have the same name. Sorry about that 😅 
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/sdushantha/pyradio/issues/4#issuecomment-1328039519
> You are receiving this because you were mentioned.
> 
> Message ID: ***@***.***>

--
